### PR TITLE
Install aws CLI globally

### PR DESCRIPTION
**Pull request by giorgiosironi**
Follow-up to https://github.com/libero/infrastructure/pull/45
after https://travis-ci.com/libero/infrastructure/builds/143721587 failed.

### CODE REVIEW

**Comment by thewilkybarkid** [comment]
Any way to move off Python 2?

**Comment by giorgiosironi** [comment]
I didn't notice. Should be easy unless the Ubuntu version is completely obsolete.

**Comment by giorgiosironi** [comment]
Python 3 packages are old (`pip` 8.x) and half-installed, so went for a self-contained Snap package:
```
$ sudo scripts/download-awscli.sh
aws-cli 1.16.266 from 'aws' installed
aws-cli/1.16.266 Python/3.5.2 Linux/4.15.0-1028-gcp botocore/1.13.2
```

**Comment by giorgiosironi** [comment]
Added `AWS_DEFAULT_REGION` to https://travis-ci.com/libero/infrastructure/settings

**Comment by giorgiosironi** [comment]
https://travis-ci.com/libero/infrastructure/builds/143738138 is green again.

**Pull request merged**
