### PR TITLE
Add elife-style-content-adapter infrastructure

### PR DESCRIPTION
**Pull request by giorgiosironi**
For https://github.com/libero/libero/issues/131#issuecomment-483250508

- S3 buckets, with public read access where necessary
- IAM setup: user, policy and credentials

Credentials are dumped in the outputs, but in an encrypted form. From there `terraform` considers updating servers out of scope, so we will need to get them into `environments`.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
I suspect that the way to go here is to create a IAM role rather than a IAM user, and then get the EC2 instance to assume that role. Though we only need a container to assume it.

**Comment by giorgiosironi** [comment]
Since we create the instances ourselves, we don't strictly need roles like in an autoscaling group. May not be worth it to [set up roles, instance profiles and continuous rotation of credentials](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html#ec2-instance-profile).

**Comment by GiancarloFusiello** [comment]
Are we ok with using the name `elife_style_content_adapter` or should these be more generic? e.g. `zips`

**Comment by giorgiosironi** [comment]
> should these be more generic? e.g. zips

Like for any database, I assume these buckets are specifically created for to the application using them, so having the name of the application helps identifying what owns them at a glance. Also helps with namespacing, as bucket names have to be unique across all AWS accounts in the world.

**Comment by giorgiosironi** [comment]
Added the `IAMFullAccess` policy to https://console.aws.amazon.com/iam/home#/groups/InfrastructureUpdates (contains the `TravisCI` IAM user) and retrying build.

**Comment by giorgiosironi** [comment]
Build green and ready to merge.

**Pull request merged**
